package projectresource

const projectGoModTpl = `module {{.Module}}

go 1.25.5
`

const projectMainTpl = `package main

import (
	"os"

	"{{.Module}}/cmd"
)

func main() {
	os.Exit(cmd.Execute(os.Args[1:]))
}
`

const projectRootCmdTpl = `package cmd

import (
	"fmt"
	"os"
)

// Execute runs the root command dispatcher.
func Execute(args []string) int {
	if len(args) > 0 && args[0] == "version" {
		fmt.Fprintln(os.Stdout, "{{.Name}} dev")
		return 0
	}
	fmt.Fprintln(os.Stdout, "{{.Name}} — use 'version' for build info")
	return 0
}
`

const projectReadmeTpl = `# {{.Name}}

Generated by agentcli project resource.
`
