version: "3"

tasks:
  fmt:
    desc: Format Go files
    cmds:
      - gofmt -w $(find . -name '*.go' -type f)

  fmt:check:
    desc: Fail when gofmt would change files
    cmds:
      - test -z "$(gofmt -l $(find . -name '*.go' -type f))"

  lint:
    desc: Run static checks
    deps: [fmt:check]
    cmds:
      - go vet ./...

  test:
    desc: Run unit tests
    deps: [fmt:check]
    cmds:
      - go test ./...

  build:
    desc: Ensure package builds
    deps: [fmt:check]
    cmds:
      - go build ./...

  smoke:
    desc: Run deterministic smoke checks
    deps: [fmt:check]
    cmds:
      - go test ./... -run 'Test(ParseArgsBasic|RunCommandSuccess|RunLifecycleOrder|ResolveExitCode)$'

  ci:
    desc: Canonical CI contract command
    deps: [lint, test, build, smoke]
    cmds:
      - echo "ci checks passed"

  verify:
    desc: Local aggregate verification
    deps: [ci]
    cmds:
      - echo "verify checks passed"
