version: "3"

tasks:
  fmt:
    desc: Format Go files
    cmds:
      - gofmt -w $(find . -name '*.go' -type f)

  fmt:check:
    desc: Fail when gofmt would change files
    cmds:
      - test -z "$(gofmt -l $(find . -name '*.go' -type f))"

  lint:
    desc: Run static checks
    deps: [fmt:check]
    cmds:
      - go vet ./...

  test:
    desc: Run unit tests
    deps: [fmt:check]
    cmds:
      - go test ./...

  build:
    desc: Ensure package builds
    deps: [fmt:check]
    cmds:
      - go build ./...

  smoke:
    desc: Run deterministic smoke checks
    deps: [fmt:check]
    cmds:
      - go test ./... -run 'Test(ParseArgsBasic|RunCommandSuccess|RunLifecycleOrder|ResolveExitCode)$'

  schema:check:
    desc: Validate JSON contracts against schemas
    deps: [fmt:check]
    cmds:
      - go run ./internal/tools/schemacheck --schema schemas/doctor-report.schema.json --input testdata/contracts/doctor-report.ok.json
      - go run ./internal/tools/schemacheck --schema schemas/scaffold-version-output.schema.json --input testdata/contracts/scaffold-version-output.ok.json

  schema:negative:
    desc: Ensure invalid contract fixtures fail validation
    deps: [fmt:check]
    cmds:
      - sh -c '! go run ./internal/tools/schemacheck --schema schemas/doctor-report.schema.json --input testdata/contracts/doctor-report.bad-missing-findings.json'
      - sh -c '! go run ./internal/tools/schemacheck --schema schemas/doctor-report.schema.json --input testdata/contracts/doctor-report.bad-schema-version.json'
      - sh -c '! go run ./internal/tools/schemacheck --schema schemas/scaffold-version-output.schema.json --input testdata/contracts/scaffold-version-output.bad-missing-date.json'
      - sh -c '! go run ./internal/tools/schemacheck --schema schemas/scaffold-version-output.schema.json --input testdata/contracts/scaffold-version-output.bad-schema-version.json'

  ci:
    desc: Canonical CI contract command
    deps: [lint, test, build, smoke, schema:check, schema:negative]
    cmds:
      - echo "ci checks passed"

  verify:
    desc: Local aggregate verification
    deps: [ci]
    cmds:
      - echo "verify checks passed"

  release:prep:
    desc: Release readiness gate (clean tree + full ci)
    deps: [ci]
    cmds:
      - test -z "$(git status --porcelain)"
      - echo "release prep passed"
