version: "3"

vars:
  GOLANGCI_LINT_VERSION: v2.4.0
  GOLANGCI_CONFIG: .golangci.yaml
  GOLANGCI_STRICT_CONFIG: .golangci.strict.yaml

tasks:
  hygiene:
    desc: Detect junk files, obvious secret leaks, and history artifacts
    cmds:
      - ./scripts/hygiene.sh

  fmt:
    desc: Format Go files
    cmds:
      - gofmt -w $(find . -name '*.go' -type f)

  fmt:check:
    desc: Fail when gofmt would change files
    cmds:
      - test -z "$(gofmt -l $(find . -name '*.go' -type f))"

  preflight:
    desc: Run baseline hygiene and format checks once
    deps: [hygiene, fmt:check]
    cmds:
      - echo "preflight checks passed"

  lint:vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  lint:golangci:
    desc: Run golangci-lint with repository config
    cmds:
      - go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}} run --config {{.GOLANGCI_CONFIG}}

  lint:strict:
    desc: Run stricter golangci profile (advisory)
    cmds:
      - go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}} run --config {{.GOLANGCI_STRICT_CONFIG}}

  lint:
    desc: Run static checks
    deps: [lint:vet, lint:golangci]
    cmds:
      - echo "lint checks passed"

  test:
    desc: Run unit tests
    cmds:
      - go test ./...

  build:
    desc: Ensure package builds
    cmds:
      - go build ./...

  smoke:
    desc: Run deterministic smoke checks
    cmds:
      - go test ./... -run 'Test(ParseArgsBasic|RunCommandSuccess|RunLifecycleOrder|ResolveExitCode)$'

  schema:check:
    desc: Validate JSON contracts against schemas
    cmds:
      - go run ./internal/tools/schemacheck --schema schemas/doctor-report.schema.json --input testdata/contracts/doctor-report.ok.json
      - go run ./internal/tools/schemacheck --schema schemas/scaffold-version-output.schema.json --input testdata/contracts/scaffold-version-output.ok.json

  schema:negative:
    desc: Ensure invalid contract fixtures fail validation
    cmds:
      - sh -c '! go run ./internal/tools/schemacheck --schema schemas/doctor-report.schema.json --input testdata/contracts/doctor-report.bad-missing-findings.json'
      - sh -c '! go run ./internal/tools/schemacheck --schema schemas/doctor-report.schema.json --input testdata/contracts/doctor-report.bad-schema-version.json'
      - sh -c '! go run ./internal/tools/schemacheck --schema schemas/scaffold-version-output.schema.json --input testdata/contracts/scaffold-version-output.bad-missing-date.json'
      - sh -c '! go run ./internal/tools/schemacheck --schema schemas/scaffold-version-output.schema.json --input testdata/contracts/scaffold-version-output.bad-schema-version.json'

  docs:check:
    desc: Fail when skill docs drift from CLI help signatures
    cmds:
      - go run ./internal/tools/doccheck --repo-root .

  regression:behavior:
    desc: Run behavior-only regression gate against committed baseline
    cmds:
      - go run ./cmd/agentcli loop regression --repo-root .

  ci:
    desc: Canonical CI contract command
    deps: [preflight, lint, test, build, smoke, schema:check, schema:negative, docs:check, regression:behavior]
    cmds:
      - echo "ci checks passed"

  verify:
    desc: Local aggregate verification
    deps: [ci]
    cmds:
      - echo "verify checks passed"

  hooks:install:
    desc: Install local git pre-commit hook for hygiene checks
    cmds:
      - mkdir -p .git/hooks
      - cp .githooks/pre-commit .git/hooks/pre-commit
      - chmod +x .git/hooks/pre-commit
      - echo "installed .git/hooks/pre-commit"
