version: "3"

vars:
  RELEASE_REPO: gh-xj/agentcli-go
  TAP_REPO: gh-xj/homebrew-tap
  TAP_BRANCH: main
  TAP_PUSH: "0"

tasks:
  fmt:
    desc: Format Go files
    cmds:
      - gofmt -w $(find . -name '*.go' -type f)

  fmt:check:
    desc: Fail when gofmt would change files
    cmds:
      - test -z "$(gofmt -l $(find . -name '*.go' -type f))"

  lint:
    desc: Run static checks
    deps: [fmt:check]
    cmds:
      - go vet ./...

  test:
    desc: Run unit tests
    deps: [fmt:check]
    cmds:
      - go test ./...

  build:
    desc: Ensure package builds
    deps: [fmt:check]
    cmds:
      - go build ./...

  smoke:
    desc: Run deterministic smoke checks
    deps: [fmt:check]
    cmds:
      - go test ./... -run 'Test(ParseArgsBasic|RunCommandSuccess|RunLifecycleOrder|ResolveExitCode)$'

  schema:check:
    desc: Validate JSON contracts against schemas
    deps: [fmt:check]
    cmds:
      - go run ./internal/tools/schemacheck --schema schemas/doctor-report.schema.json --input testdata/contracts/doctor-report.ok.json
      - go run ./internal/tools/schemacheck --schema schemas/scaffold-version-output.schema.json --input testdata/contracts/scaffold-version-output.ok.json

  schema:negative:
    desc: Ensure invalid contract fixtures fail validation
    deps: [fmt:check]
    cmds:
      - sh -c '! go run ./internal/tools/schemacheck --schema schemas/doctor-report.schema.json --input testdata/contracts/doctor-report.bad-missing-findings.json'
      - sh -c '! go run ./internal/tools/schemacheck --schema schemas/doctor-report.schema.json --input testdata/contracts/doctor-report.bad-schema-version.json'
      - sh -c '! go run ./internal/tools/schemacheck --schema schemas/scaffold-version-output.schema.json --input testdata/contracts/scaffold-version-output.bad-missing-date.json'
      - sh -c '! go run ./internal/tools/schemacheck --schema schemas/scaffold-version-output.schema.json --input testdata/contracts/scaffold-version-output.bad-schema-version.json'

  ci:
    desc: Canonical CI contract command
    deps: [lint, test, build, smoke, schema:check, schema:negative]
    cmds:
      - echo "ci checks passed"

  verify:
    desc: Local aggregate verification
    deps: [ci]
    cmds:
      - echo "verify checks passed"

  release:prep:
    desc: Release readiness gate (clean tree + full ci)
    deps: [ci]
    cmds:
      - test -z "$(git status --porcelain)"
      - echo "release prep passed"

  release:build:
    desc: Build multi-arch release artifacts into dist/{{.VERSION}}
    requires:
      vars: [VERSION]
    cmds:
      - test -n "{{.VERSION}}"
      - |
        sh -c 'case "{{.VERSION}}" in
          v*) ;;
          *) echo "VERSION must start with v (example v0.2.2)" >&2; exit 1 ;;
        esac'
      - mkdir -p dist/{{.VERSION}}
      - |
        set -euo pipefail
        for target in "darwin amd64" "darwin arm64" "linux amd64" "linux arm64"; do
          os=$(echo "$target" | awk '{print $1}')
          arch=$(echo "$target" | awk '{print $2}')
          outdir="dist/{{.VERSION}}/agentcli_${os}_${arch}"
          mkdir -p "$outdir"
          GOOS="$os" GOARCH="$arch" CGO_ENABLED=0 go build -o "$outdir/agentcli" ./cmd/agentcli
          cp LICENSE "$outdir/"
          tar -C "dist/{{.VERSION}}" -czf "dist/{{.VERSION}}/agentcli_{{.VERSION}}_${os}_${arch}.tar.gz" "agentcli_${os}_${arch}"
        done
      - sh -c 'cd dist/{{.VERSION}} && shasum -a 256 agentcli_{{.VERSION}}_*.tar.gz > checksums.txt'
      - echo "release artifacts prepared in dist/{{.VERSION}}"

  release:tag:
    desc: Create and push git tag for VERSION
    requires:
      vars: [VERSION]
    cmds:
      - test -n "{{.VERSION}}"
      - git tag -a {{.VERSION}} -m "{{.VERSION}}"
      - git push origin {{.VERSION}}

  release:publish:
    desc: Create GitHub release for VERSION using docs/releases/{{.VERSION}}.md
    requires:
      vars: [VERSION]
    cmds:
      - test -n "{{.VERSION}}"
      - test -f docs/releases/{{.VERSION}}.md
      - test -f dist/{{.VERSION}}/checksums.txt
      - >
        gh release create {{.VERSION}}
        dist/{{.VERSION}}/agentcli_{{.VERSION}}_darwin_amd64.tar.gz
        dist/{{.VERSION}}/agentcli_{{.VERSION}}_darwin_arm64.tar.gz
        dist/{{.VERSION}}/agentcli_{{.VERSION}}_linux_amd64.tar.gz
        dist/{{.VERSION}}/agentcli_{{.VERSION}}_linux_arm64.tar.gz
        dist/{{.VERSION}}/checksums.txt
        --repo {{.RELEASE_REPO}}
        --title "agentcli-go {{.VERSION}}"
        --notes-file docs/releases/{{.VERSION}}.md

  release:verify:
    desc: Verify published release assets and digests match uploaded checksums.txt
    requires:
      vars: [VERSION]
    cmds:
      - test -n "{{.VERSION}}"
      - >
        gh release view {{.VERSION}}
        --repo {{.RELEASE_REPO}}
        --json isDraft,isPrerelease
        --jq '.isDraft == false and .isPrerelease == false' | grep -q true
      - |
        set -euo pipefail
        tmp="$(mktemp -d)"
        gh release download {{.VERSION}} --repo {{.RELEASE_REPO}} --pattern checksums.txt --dir "$tmp"
        checksums_file="$tmp/checksums.txt"
        test -f "$checksums_file"
        while read -r checksum name; do
          digest=$(gh release view {{.VERSION}} --repo {{.RELEASE_REPO}} --json assets --jq ".assets[] | select(.name==\"${name}\") | .digest")
          test -n "$digest"
          test "$digest" = "sha256:${checksum}"
        done < "$checksums_file"
        checksums_digest=$(gh release view {{.VERSION}} --repo {{.RELEASE_REPO}} --json assets --jq '.assets[] | select(.name=="checksums.txt") | .digest')
        test -n "$checksums_digest"
      - echo "release verify passed for {{.VERSION}}"

  release:tap:
    desc: Update homebrew tap formula for VERSION (set TAP_PUSH=1 to commit and push)
    requires:
      vars: [VERSION]
    cmds:
      - test -n "{{.VERSION}}"
      - |
        sh -c 'case "{{.VERSION}}" in
          v*) ;;
          *) echo "VERSION must start with v (example v0.2.2)" >&2; exit 1 ;;
        esac'
      - |
        set -euo pipefail
        tmp="$(mktemp -d)"
        git clone "https://github.com/{{.TAP_REPO}}.git" "$tmp/homebrew-tap" >/dev/null
        formula="$tmp/homebrew-tap/Formula/agentcli.rb"
        sha=$(curl -L -s "https://github.com/gh-xj/agentcli-go/archive/refs/tags/{{.VERSION}}.tar.gz" | shasum -a 256 | awk '{print $1}')
        awk -v v="{{.VERSION}}" -v s="$sha" '
          /^  url "/ { print "  url \"https://github.com/gh-xj/agentcli-go/archive/refs/tags/" v ".tar.gz\""; next }
          /^  sha256 "/ { print "  sha256 \"" s "\""; next }
          { print }
        ' "$formula" > "$formula.tmp"
        mv "$formula.tmp" "$formula"
        cd "$tmp/homebrew-tap"
        if git diff --quiet -- Formula/agentcli.rb; then
          echo "tap formula already up to date for {{.VERSION}}"
          exit 0
        fi
        if [ "{{.TAP_PUSH}}" = "1" ]; then
          version_no_v="{{.VERSION}}"
          version_no_v="${version_no_v#v}"
          git add Formula/agentcli.rb
          git commit -m "agentcli ${version_no_v}"
          git push origin "{{.TAP_BRANCH}}"
          echo "tap updated and pushed"
        else
          echo "tap update preview (set TAP_PUSH=1 to push):"
          git --no-pager diff -- Formula/agentcli.rb
        fi

  release:
    desc: End-to-end release flow (prep + build + tag + publish + verify)
    requires:
      vars: [VERSION]
    cmds:
      - task: release:prep
      - task: release:build
        vars:
          VERSION: "{{.VERSION}}"
      - task: release:tag
        vars:
          VERSION: "{{.VERSION}}"
      - task: release:publish
        vars:
          VERSION: "{{.VERSION}}"
      - task: release:verify
        vars:
          VERSION: "{{.VERSION}}"

  release:all:
    desc: End-to-end release plus Homebrew tap update (set TAP_PUSH=1 to push tap change)
    requires:
      vars: [VERSION]
    cmds:
      - task: release
        vars:
          VERSION: "{{.VERSION}}"
      - task: release:tap
        vars:
          VERSION: "{{.VERSION}}"
          TAP_PUSH: "{{.TAP_PUSH}}"

  loop:run:
    desc: Run onboarding scenario and emit report artifacts
    cmds:
      - go run ./cmd/agentcli loop run --repo-root . --threshold 9.0 --max-iterations 1

  loop:serve:
    desc: Start local loop API server
    cmds:
      - go run ./cmd/agentcli loop-server --addr 127.0.0.1:7878 --repo-root .

  loop:judge:
    desc: Run onboarding judge-only gate
    cmds:
      - go run ./cmd/agentcli loop judge --repo-root . --threshold 9.0 --max-iterations 1

  loop:judge:api:
    desc: Run onboarding judge via local loop API
    cmds:
      - go run ./cmd/agentcli loop judge --api http://127.0.0.1:7878 --repo-root . --threshold 9.0 --max-iterations 1

  loop:autofix:
    desc: Run onboarding loop with autofix and branch commit workflow
    cmds:
      - go run ./cmd/agentcli loop autofix --repo-root . --threshold 9.0 --max-iterations 3

  loop:all:
    desc: Full onboarding reinforcement loop
    cmds:
      - go run ./cmd/agentcli loop all --repo-root . --threshold 9.0 --max-iterations 3

  loop:evolve:
    desc: Project skill trigger (local evolve loop + push branch + open/update PR)
    cmds:
      - BASE_BRANCH={{.BASE_BRANCH | default "main"}} LOOP_BRANCH={{.LOOP_BRANCH | default "autofix/onboarding-loop"}} THRESHOLD={{.THRESHOLD | default "9.0"}} MAX_ITERATIONS={{.MAX_ITERATIONS | default "5"}} scripts/skill-loop/run.sh
