// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/gh-xj/agentcli-go/dal"
	"github.com/gh-xj/agentcli-go/operator"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeContainer is the Wire injector that constructs a fully wired Container.
func InitializeContainer() *Container {
	fileSystemImpl := dal.NewFileSystem()
	executorImpl := dal.NewExecutor()
	loggerImpl := dal.NewLogger()
	templateOperatorImpl := operator.NewTemplateOperator(fileSystemImpl)
	complianceOperatorImpl := operator.NewComplianceOperator(fileSystemImpl)
	argsOperatorImpl := operator.NewArgsOperator()
	scaffoldService := NewScaffoldService(templateOperatorImpl, complianceOperatorImpl, fileSystemImpl, executorImpl)
	doctorService := NewDoctorService(complianceOperatorImpl, fileSystemImpl)
	lifecycleService := NewLifecycleService()
	container := NewContainer(fileSystemImpl, executorImpl, loggerImpl, templateOperatorImpl, complianceOperatorImpl, argsOperatorImpl, scaffoldService, doctorService, lifecycleService)
	return container
}

// wire.go:

// ProviderSet is the Wire provider set for the service layer.
var ProviderSet = wire.NewSet(dal.NewFileSystem, wire.Bind(new(dal.FileSystem), new(*dal.FileSystemImpl)), dal.NewExecutor, wire.Bind(new(dal.Executor), new(*dal.ExecutorImpl)), dal.NewLogger, wire.Bind(new(dal.Logger), new(*dal.LoggerImpl)), operator.NewTemplateOperator, wire.Bind(new(operator.TemplateOperator), new(*operator.TemplateOperatorImpl)), operator.NewComplianceOperator, wire.Bind(new(operator.ComplianceOperator), new(*operator.ComplianceOperatorImpl)), operator.NewArgsOperator, wire.Bind(new(operator.ArgsOperator), new(*operator.ArgsOperatorImpl)), NewScaffoldService,
	NewDoctorService,
	NewLifecycleService,
	NewContainer,
)
