#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
BASE_BRANCH="${BASE_BRANCH:-main}"
LOOP_BRANCH="${LOOP_BRANCH:-autofix/onboarding-loop}"
THRESHOLD="${THRESHOLD:-9.0}"
MAX_ITERATIONS="${MAX_ITERATIONS:-5}"
SOURCE_REF="${SOURCE_REF:-origin/${BASE_BRANCH}}"
WORKTREE_DIR="${WORKTREE_DIR:-/tmp/agentcli-evolve-$(date +%Y%m%d-%H%M%S)}"
DRY_RUN="${DRY_RUN:-0}"

log() {
  printf '[loop-skill] %s\n' "$*"
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "missing required command: $1" >&2
    exit 2
  fi
}

require_cmd git
require_cmd go

log "repo: ${REPO_ROOT}"
log "base branch: ${BASE_BRANCH}"
log "source ref: ${SOURCE_REF}"
log "loop branch: ${LOOP_BRANCH}"
log "threshold: ${THRESHOLD}"
log "max iterations: ${MAX_ITERATIONS}"
log "worktree: ${WORKTREE_DIR}"
log "dry run: ${DRY_RUN}"

cd "${REPO_ROOT}"
if [[ "${SOURCE_REF}" == origin/* ]]; then
  git fetch origin "${BASE_BRANCH}"
fi

if git worktree list | grep -q "${WORKTREE_DIR}"; then
  echo "worktree already exists: ${WORKTREE_DIR}" >&2
  exit 2
fi

EXISTING_BRANCH_WT="$(
  git worktree list --porcelain | awk -v b="refs/heads/${LOOP_BRANCH}" '
    $1=="worktree" { wt=$2 }
    $1=="branch" && $2==b { print wt }
  '
)"
if [[ -n "${EXISTING_BRANCH_WT}" ]]; then
  log "removing stale worktree using ${LOOP_BRANCH}: ${EXISTING_BRANCH_WT}"
  git worktree remove "${EXISTING_BRANCH_WT}" --force || true
fi

cleanup() {
  if [[ "${KEEP_WORKTREE:-0}" != "1" ]]; then
    git worktree remove "${WORKTREE_DIR}" --force >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

if git show-ref --verify --quiet "refs/heads/${LOOP_BRANCH}"; then
  git branch -D "${LOOP_BRANCH}" >/dev/null 2>&1 || true
fi

git worktree add -b "${LOOP_BRANCH}" "${WORKTREE_DIR}" "${SOURCE_REF}" >/dev/null

cd "${WORKTREE_DIR}"
log "running local evolve loop"
go run ./cmd/agentcli loop all --repo-root . --threshold "${THRESHOLD}" --max-iterations "${MAX_ITERATIONS}" --branch "${LOOP_BRANCH}"

SUMMARY_FILE="${WORKTREE_DIR}/.docs/onboarding-loop/latest-summary.json"
if [[ ! -f "${SUMMARY_FILE}" ]]; then
  echo "missing summary file: ${SUMMARY_FILE}" >&2
  exit 3
fi

PASS="$(grep -E '"pass":[[:space:]]*(true|false)' "${SUMMARY_FILE}" | head -n1 | sed -E 's/.*"pass":[[:space:]]*(true|false).*/\1/')"
SCORE="$(grep -E '"score":[[:space:]]*[0-9.]+' "${SUMMARY_FILE}" | head -n1 | sed -E 's/.*"score":[[:space:]]*([0-9.]+).*/\1/')"
log "judge score: ${SCORE:-unknown}, pass: ${PASS:-unknown}"

if [[ "${PASS}" != "true" ]]; then
  echo "judge did not pass threshold" >&2
  exit 4
fi

log "pushing branch"
if [[ "${DRY_RUN}" = "1" ]]; then
  log "dry run: skip push"
else
  git push -u origin "${LOOP_BRANCH}" --force-with-lease
fi

if [[ "${DRY_RUN}" = "1" ]]; then
  log "dry run: skip PR creation"
elif command -v gh >/dev/null 2>&1; then
  log "creating/updating PR"
  PR_NUMBER="$(gh pr list --base "${BASE_BRANCH}" --head "${LOOP_BRANCH}" --state open --json number --jq '.[0].number' 2>/dev/null || true)"
  PR_BODY=$'## Auto Evolution Loop\n\nThis PR was generated by `scripts/skill-loop/run.sh`.\n\n- Local loop executed\n- Judge score reached threshold\n- Autofix commits applied on dedicated branch\n\nPlease review and merge manually (human-in-the-loop).'
  if [[ -z "${PR_NUMBER}" || "${PR_NUMBER}" == "null" ]]; then
    gh pr create \
      --base "${BASE_BRANCH}" \
      --head "${LOOP_BRANCH}" \
      --title "chore: evolve product via local verification loop" \
      --body "${PR_BODY}" >/dev/null
  else
    gh pr edit "${PR_NUMBER}" --title "chore: evolve product via local verification loop" --body "${PR_BODY}" >/dev/null
  fi
  PR_URL="$(gh pr list --base "${BASE_BRANCH}" --head "${LOOP_BRANCH}" --state open --json url --jq '.[0].url')"
  log "pr ready: ${PR_URL}"
else
  log "gh not installed; skipping PR creation"
fi

log "done"
